server:
  port: 9010
spring:
  application:
    name: user-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc-security?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true