server:
  port: 9010
  ssl:
    key-store: classpath:jojo.key
    key-store-password: 123456
    key-password: 123456
spring:
  application:
    name: user-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc-security?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: yucn1227
  jpa:
    show-sql: true
    generate-ddl: true